### ISSUE TITLE
Look into making api rate limits configurable

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#299]
Spawned from review of #286

**Comment by jspaaks** [comment]
What about making this part of the default `.howfairis.yml`? Something like

```yaml

- github:
  - authenticated:
    - api: "5000,3600"
    - raw:
    - frontend: 
  - unauthenticated:
    - api: "60,3600"
    - raw:
    - frontend: 
- gitlab:
  - authenticated:
    - api: "2000,60"
    - raw:
    - frontend: 
  - unauthenticated:
    - api: "500,60"
    - raw:
    - frontend: 
```
