### ISSUE TITLE
Drop force support

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#63]
I added https://github.com/3D-e-Chem/kripodb/blob/master/.howfairis.yml with
```yaml
force:
  repository: true
  license: true
  registry: true
  citation: true
  checklist: true
include_comments: false
```

Now the checks are bypassed and I get 100% compliance. 

As someone who wants to assert how fair a piece of software is I would like to trust the badge, but by allowing it to report 100% due to a config file setup by the repo owner, I can not trust the tool. As it will report whatever the repo owner wants.

Dropping support for force would improve my trust as the repo owner has to do the work, not me. If a repo owner thinks he/she should get more compliance then they should make a PR to fix the howfairis tool so it checks the repo correctly.
